-- Development seed data. Run against a freshly initialized database.
-- The password hash below is a placeholder; replace it with a hash generated by
-- werkzeug.security.generate_password_hash before logging in as the demo user.

INSERT INTO users (full_name, email, phone, password_hash, weather_alerts_enabled, unit_system)
VALUES ('Demo User', 'demo@farm.local', '555-0000', 'REPLACE_WITH_WERKZEUG_PASSWORD_HASH', 0, 'metric');

INSERT INTO market_areas (area_name, region) VALUES
('Nakuru Central', 'Nakuru County'),
('Nakuru North', 'Nakuru County'),
('Naivasha', 'Nakuru County');

INSERT INTO farms (user_id, market_area_id, farm_name, location, total_area_acres, latitude, longitude)
SELECT u.user_id, m.market_area_id, 'Moses Farm', 'Nakuru, Kenya', 3.0, -0.283, 35.997
FROM users u
CROSS JOIN market_areas m
WHERE u.email = 'demo@farm.local' AND m.area_name = 'Nakuru Central';

INSERT INTO fields (farm_id, field_name, area_acres, soil_type, notes)
SELECT f.farm_id, v.field_name, v.area_acres, v.soil_type, v.notes
FROM farms f
JOIN users u ON u.user_id = f.user_id
JOIN (VALUES
    ('Field 1', 1.5, 'Loam', ''),
    ('Field 2', 1.0, 'Clay', ''),
    ('Field 3', 0.5, 'Sandy Loam', '')
) AS v(field_name, area_acres, soil_type, notes)
WHERE u.email = 'demo@farm.local' AND f.farm_name = 'Moses Farm';

INSERT INTO crops (farm_id, field_id, crop_name, variety, planting_date, expected_harvest_date, area_acres, status)
SELECT f.farm_id, fi.field_id, v.crop_name, v.variety, v.planting_date, v.expected_harvest_date, v.area_acres, 'growing'
FROM farms f
JOIN users u ON u.user_id = f.user_id
JOIN (VALUES
    ('Field 1', 'Maize', 'H614', date('now', '-33 days'), date('now', '+35 days'), 1.5),
    ('Field 2', 'Beans', 'Rosecoco', date('now', '-15 days'), date('now', '+25 days'), 1.0),
    ('Field 3', 'Kale', 'Sukuma Wiki', date('now', '-45 days'), date('now', '+15 days'), 0.5)
) AS v(field_name, crop_name, variety, planting_date, expected_harvest_date, area_acres)
JOIN fields fi ON fi.farm_id = f.farm_id AND fi.field_name = v.field_name
WHERE u.email = 'demo@farm.local' AND f.farm_name = 'Moses Farm';

INSERT INTO activities (farm_id, crop_id, activity_date, activity_type, crop_name, input_used, quantity, notes)
SELECT c.farm_id, c.crop_id, v.activity_date, v.activity_type, c.crop_name, v.input_used, v.quantity, v.notes
FROM crops c
JOIN farms f ON f.farm_id = c.farm_id
JOIN users u ON u.user_id = f.user_id
JOIN (VALUES
    ('Maize', date('now', '-2 days'), 'Fertilizer application', 'DAP', '50kg', ''),
    ('Beans', date('now', '-4 days'), 'Weeding', '', '', ''),
    ('Kale', date('now', '-5 days'), 'Irrigation', 'Water', '200L', ''),
    ('Maize', date('now', '-7 days'), 'Pest control', 'Pesticide', '2L', '')
) AS v(crop_name, activity_date, activity_type, input_used, quantity, notes)
WHERE u.email = 'demo@farm.local' AND f.farm_name = 'Moses Farm' AND c.crop_name = v.crop_name;

INSERT INTO soil_tests (farm_id, field_id, test_date, soil_type, ph, nitrogen, phosphorus, potassium, organic_matter, moisture, notes)
SELECT f.farm_id, fi.field_id, date('now', '-20 days'), 'Loam', 6.4, 28, 15, 110, 2.6, 22, ''
FROM farms f
JOIN users u ON u.user_id = f.user_id
JOIN fields fi ON fi.farm_id = f.farm_id AND fi.field_name = 'Field 1'
WHERE u.email = 'demo@farm.local' AND f.farm_name = 'Moses Farm';
